version: "3.3"

services:  
    
    db:
        image: postgres:12.2-alpine
        environment:
            - POSTGRES_USER=taskflow
            - POSTGRES_PASSWORD=ef3e597c3effdacfbee881dab45db291128689e4
            - POSTGRES_DB=taskflow
        volumes:
            - db:/var/lib/postgresql/data
    
    back-end:
        build:
            context: back-end/
            dockerfile: build.Dockerfile
        environment:
            - spring.datasource.url=jdbc:postgresql://db:5432/taskflow
            - spring.datasource.username=taskflow
            - spring.datasource.password=ef3e597c3effdacfbee881dab45db291128689e4
            - flyway.url=jdbc:postgresql://db:5432/taskflow
            - flyway.schemas=public
            - flyway.user=taskflow
            - flyway.password=ef3e597c3effdacfbee881dab45db291128689e4
        ports:
            - 8080:8080
        depends_on:
            - db

    front-end:
        build:
            context: front-end/
            dockerfile: build.Dockerfile
        ports:
            - 3000:80
        depends_on:
            - back-end
volumes:
  db: